// This file is auto-generated by scripts/generate.ts
// Do not edit manually

import type { ProviderWithModels, Model } from '../types';

export const provider: ProviderWithModels = {"id":"parasail","name":"Parasail","region":"US","url":"https://www.parasail.io","api_url":"https://api.parasail.io/v1","docs_url":"https://docs.parasail.io/parasail-docs","pricing_url":"https://www.parasail.io/pricing","description":"AI inference and compute platform providing serverless OpenAI-compatible access to popular models.","type":"cloud","models_url":"https://api.parasail.io/v1/models","openai_compatible":true,"free_tier":false,"github_url":"https://github.com/parasail-ai","twitter_url":"https://x.com/parasail_ai","icon":"<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 24 24\" fill=\"currentColor\" fill-rule=\"evenodd\">\n  <path d=\"M0 15.852c4.5 0 8.147 3.648 8.147 8.148H0v-8.148z\"></path><path clip-rule=\"evenodd\" d=\"M0 7.688v.018C9 7.706 16.294 15 16.294 24h.019l-.018-.036c3.33-.2 8.864-2.447 7.49-9.58A19.95 19.95 0 009.61.213C2.482-1.155.235 4.374.036 7.704L0 7.688z\"></path>\n</svg>","models":[]};

export const models: Model[] = provider.models.map((m) => ({ ...m, provider: provider.id }));
