// This file is auto-generated by scripts/generate.ts
// Do not edit manually

import type { ProviderWithModels, Model } from '../types';

export const provider: ProviderWithModels = {"id":"siliconflow","name":"SiliconFlow","aliases":["siliconcloud"],"region":"CN","url":"https://www.siliconflow.com","api_url":"https://api.siliconflow.com/v1","docs_url":"https://docs.siliconflow.com","pricing_url":"https://cloud.siliconflow.com/pricing","description":"Inference cloud platform offering OpenAI-compatible APIs for language, image, audio, video, embedding, and reranking models.","type":"cloud","models_url":"https://api.siliconflow.com/v1/models","openai_compatible":true,"free_tier":false,"status_url":"https://status.siliconflow.com","icon":"<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 24 24\" fill=\"currentColor\" fill-rule=\"evenodd\">\n  <path clip-rule=\"evenodd\" d=\"M22.956 6.521H12.522c-.577 0-1.044.468-1.044 1.044v3.13c0 .577-.466 1.044-1.043 1.044H1.044c-.577 0-1.044.467-1.044 1.044v4.174C0 17.533.467 18 1.044 18h10.434c.577 0 1.044-.467 1.044-1.043v-3.13c0-.578.466-1.044 1.043-1.044h9.391c.577 0 1.044-.467 1.044-1.044V7.565c0-.576-.467-1.044-1.044-1.044z\"></path>\n</svg>","models":[]};

export const models: Model[] = provider.models.map((m) => ({ ...m, provider: provider.id }));
