packages:
  - apps/*
  - packages/*

catalog:
  # React
  "@vercel/analytics": ^2.0.1
  react: ^19.2.5
  react-dom: ^19.2.5

  # Next.js
  next: ^16.2.3
  react-grab: ^0.1.31

  # TypeScript
  typescript: ^6.0.2

  # Tailwind CSS
  tailwindcss: ^4.2.2
  "@tailwindcss/postcss": ^4.2.2

  # Hono
  hono: ^4.12.12

  # Cloudflare
  wrangler: ^4.81.1

  # Types
  "@types/node": ^25.6.0
  "@types/react": ^19.2.14
  "@types/react-dom": ^19.2.3
