import * as fs from "node:fs";
import * as path from "node:path";

const ROOT = path.resolve(import.meta.dirname, "..");
const PROVIDERS_DIR = path.join(ROOT, "providers");
const OUTPUT_FILE = path.join(ROOT, "src", "data.ts");

function generate() {
  const providerDirs = fs
    .readdirSync(PROVIDERS_DIR, { withFileTypes: true })
    .filter((d) => d.isDirectory())
    .map((d) => d.name)
    .sort();

  const providers: Array<{
    provider: Record<string, unknown>;
    models: Record<string, unknown>[];
  }> = [];

  for (const dir of providerDirs) {
    const providerPath = path.join(PROVIDERS_DIR, dir, "_provider.json");
    if (!fs.existsSync(providerPath)) continue;

    const provider = JSON.parse(fs.readFileSync(providerPath, "utf-8"));

    // Read icon.svg if present
    const iconPath = path.join(PROVIDERS_DIR, dir, "icon.svg");
    if (fs.existsSync(iconPath)) {
      provider.icon = fs.readFileSync(iconPath, "utf-8").trim();
    }

    const modelsDir = path.join(PROVIDERS_DIR, dir, "models");
    const models: Record<string, unknown>[] = [];

    if (fs.existsSync(modelsDir)) {
      const modelFiles = fs
        .readdirSync(modelsDir)
        .filter((f) => f.endsWith(".json"))
        .sort();

      for (const file of modelFiles) {
        const model = JSON.parse(
          fs.readFileSync(path.join(modelsDir, file), "utf-8"),
        );
        // Strip internal metadata from generated output
        delete model._generated;
        models.push(model);
      }
    }

    providers.push({ provider, models });
  }

  const data = providers.map(({ provider, models }) => ({
    ...provider,
    models,
  }));

  const lines = [
    "// This file is auto-generated by scripts/generate.ts",
    "// Do not edit manually",
    "",
    "import type { ProviderWithModels, Model } from './types';",
    "",
    `export const providers: ProviderWithModels[] = ${JSON.stringify(data, null, 2)};`,
    "",
    "export const allModels: Model[] = providers.flatMap((p) =>",
    "  p.models.map((m) => ({ ...m, provider: p.id }))",
    ");",
    "",
  ];

  fs.writeFileSync(OUTPUT_FILE, lines.join("\n"), "utf-8");

  const totalModels = providers.reduce((sum, p) => sum + p.models.length, 0);
  console.log(
    `Generated ${path.relative(ROOT, OUTPUT_FILE)} with ${providers.length} providers and ${totalModels} models`,
  );
}

generate();
