import * as fs from "node:fs";
import * as path from "node:path";

const ROOT = path.resolve(import.meta.dirname, "..");
const PROVIDERS_DIR = path.join(ROOT, "providers");
const NPM_DIR = path.resolve(ROOT, "..", "npm");
const DATA_OUTPUT = path.join(ROOT, "src", "data.ts");
const NPM_OUTPUT = path.join(NPM_DIR, "src", "data.ts");
const PROVIDERS_OUT_DIR = path.join(NPM_DIR, "src", "providers");

function generate() {
  const providerDirs = fs
    .readdirSync(PROVIDERS_DIR, { withFileTypes: true })
    .filter((d) => d.isDirectory())
    .map((d) => d.name)
    .sort();

  const providers: Array<{
    id: string;
    provider: Record<string, unknown>;
    models: Record<string, unknown>[];
  }> = [];

  for (const dir of providerDirs) {
    const providerPath = path.join(PROVIDERS_DIR, dir, "_provider.json");
    if (!fs.existsSync(providerPath)) continue;

    const provider = JSON.parse(fs.readFileSync(providerPath, "utf-8"));

    // Read icon.svg if present
    const iconPath = path.join(PROVIDERS_DIR, dir, "icon.svg");
    if (fs.existsSync(iconPath)) {
      provider.icon = fs.readFileSync(iconPath, "utf-8").trim();
    }

    const modelsDir = path.join(PROVIDERS_DIR, dir, "models");
    const models: Record<string, unknown>[] = [];

    if (fs.existsSync(modelsDir)) {
      const modelFiles = fs
        .readdirSync(modelsDir)
        .filter((f) => f.endsWith(".json"))
        .sort();

      for (const file of modelFiles) {
        const model = JSON.parse(
          fs.readFileSync(path.join(modelsDir, file), "utf-8"),
        );
        // Strip internal/runtime fields from generated output
        delete model._generated;
        delete model.provider;
        models.push(model);
      }
    }

    providers.push({ id: dir, provider, models });
  }

  // 1. Generate main data.ts (all providers)
  const allData = providers.map(({ provider, models }) => ({
    ...provider,
    models,
  }));

  const mainLines = [
    "// This file is auto-generated by scripts/generate.ts",
    "// Do not edit manually",
    "",
    "import type { ProviderWithModels, Model } from './types';",
    "",
    `export const providers: ProviderWithModels[] = ${JSON.stringify(allData, null, 2)};`,
    "",
    "export const allModels: Model[] = providers.flatMap((p) =>",
    "  p.models.map((m) => ({ ...m, provider: p.id }))",
    ");",
    "",
  ];

  // Write to data/src (for internal apps — single file with all data)
  fs.writeFileSync(DATA_OUTPUT, mainLines.join("\n"), "utf-8");

  // 2. Generate per-provider files (modelpedia/openai, modelpedia/anthropic, etc.)
  fs.mkdirSync(PROVIDERS_OUT_DIR, { recursive: true });

  for (const { id, provider, models } of providers) {
    const providerData = { ...provider, models };
    const providerLines = [
      "// This file is auto-generated by scripts/generate.ts",
      "// Do not edit manually",
      "",
      "import type { ProviderWithModels, Model } from '../types';",
      "",
      `export const provider: ProviderWithModels = ${JSON.stringify(providerData)};`,
      "",
      "export const models: Model[] = provider.models.map((m) => ({ ...m, provider: provider.id }));",
      "",
    ];

    fs.writeFileSync(
      path.join(PROVIDERS_OUT_DIR, `${id}.ts`),
      providerLines.join("\n"),
      "utf-8",
    );
  }

  // 3. Generate npm/src/data.ts — aggregates from per-provider files
  const providerIds = providers.map((p) => p.id);
  const npmDataLines = [
    "// This file is auto-generated by scripts/generate.ts",
    "// Do not edit manually",
    "",
    "import type { ProviderWithModels, Model } from './types';",
    ...providerIds.map(
      (id) => `import { provider as ${id.replace(/[^a-zA-Z0-9]/g, "_")} } from './providers/${id}';`,
    ),
    "",
    `export const providers: ProviderWithModels[] = [${providerIds.map((id) => id.replace(/[^a-zA-Z0-9]/g, "_")).join(", ")}];`,
    "",
    "export const allModels: Model[] = providers.flatMap((p) =>",
    "  p.models.map((m) => ({ ...m, provider: p.id }))",
    ");",
    "",
  ];
  fs.writeFileSync(NPM_OUTPUT, npmDataLines.join("\n"), "utf-8");

  const totalModels = providers.reduce((sum, p) => sum + p.models.length, 0);
  console.log(
    `Generated ${providers.length} providers (${totalModels} models) → data.ts + ${providers.length} provider files`,
  );
}

generate();
